### ISSUE TITLE
styling issue of the footer on forms/details-source.xml

### ISSUE THREAD

**Issue by peterstadler** [Edirom/MerMEId#182]
the footer of `forms/details-source.xml` apparently misses some CSS, see Screenshot and compare with the landing page at `index.html`:
<img width="1153" alt="Bildschirmfoto 2023-11-16 um 14 38 51" src="https://github.com/Edirom/MerMEId/assets/2247936/9b33de3c-779e-4ead-a13b-9cfa75e488ad">

**Comment by daniel-jettka** [comment]
due to an issue with the contrast on the details pages with a very light colored background I would propose option (a) to make the font color in the footer lighter. An alternative would be option (b) to have different CSS directives for different background colors.

This is what it looks like with a lighter font color:

![image](https://github.com/Edirom/MerMEId/assets/18614293/627620a8-aa14-4760-8f23-4527c77b73e3)

![image](https://github.com/Edirom/MerMEId/assets/18614293/0936a48b-6c11-4c5e-8f24-828178d6ff41)
