### ISSUE TITLE
post-install.xq should only run the permission changes once

### ISSUE THREAD

**Issue by MauPalantir** [Edirom/MerMEId#19]
To prevent overwriting user configuration.

**Comment by peterstadler** [comment]
During [MMCC#3](https://github.com/Edirom/MerMEId/wiki/2021-02-15-MerMEId-Community-Call-%233) we decided that this is blocked by #49

**Comment by peterstadler** [comment]
I believe this is already fixed by #59. 
With https://github.com/Edirom/MerMEId/blob/851f579fb3c3e2f57755c2986dc3f0328e099514/post-install.xql#L105 we check whether this is the first run and execute the following code parts only iff the "mermedit" group (which gets created on first run) does not exist.
