### ISSUE TITLE
graphic bugs in the input mask

### ISSUE THREAD

**Issue by gucl-mu** [Edirom/MerMEId#39]
I found some graphic glitches in the input mask. It mainly affects the widgets that can be opened separately and do not belong to the main mask (date-widget, settings-widget).  Most of the time the click boxes are no longer visible. Maybe a simple adjustment in the CSS will solve it. Here are a few examples:
![Klickboxen](https://user-images.githubusercontent.com/67600420/101881673-08e01080-3b95-11eb-8af6-44c46b006bdc.JPG)
![speichern](https://user-images.githubusercontent.com/67600420/101881767-2d3bed00-3b95-11eb-93ad-49d10906948a.JPG)
![date verschoben](https://user-images.githubusercontent.com/67600420/101881810-3f1d9000-3b95-11eb-94af-e04ceac35e99.JPG)

Also, the title of the respective tab always seems to overlap:
![Titel verschoben](https://user-images.githubusercontent.com/67600420/101882477-3d080100-3b96-11eb-831a-e52ba9f4d8cf.png)

**Comment by daniel-jettka** [comment]
Reproduce: 
- start MerMEId, inspect cases (CSS) described above in browser ("Inspect element")
- have a look at them in different browsers

Fix: 
- insert specific CSS rules for the cases that overwrite the ugly stuff

**Comment by daniel-jettka** [comment]
1. Settings form:
- could potentially be fixed by 
`.orbeon div#settings-dialog div.xxforms-dialog-body span.xforms-group {
    line-height: 2em;
}

.orbeon div#settings-dialog label.checkbox input[type="checkbox"] {
    margin: 0;
    float: left;
}`
- not sure where to insert in the source...

2. underlines in top menu
- potentially fixed by:
`.orbeon div#top-bar p#view_menu a {
    text-decoration: none;      
}`
- not sure where to insert this in the source...

3. date form

4. title

**Comment by daniel-jettka** [comment]
@AnastasiaWawilow had a look to the appearance on different OS (macos, windows) and different browsers (chrome, safari, edge, firefox) - the issues seem to be browser-independent.

**Comment by DILewis** [comment]
There looks to be a structural difference in the top menu case. 
The icons that work are of the form `<span class="xforms-trigger"><a><img...`
Those that don't are of the form `<a class="xforms-trigger"><img` with no containing `span`.
The CSS rule that turns off underlining is `.orbeon .xforms-trigger a` in `xform_style.css`.
To me that suggests that the consistent solution might be in the html structure rather than CSS.

**Comment by daniel-jettka** [comment]
> To me that suggests that the consistent solution might be in the html structure rather than CSS.

This was my impression too, but the buttons which appear as `<span class="xforms-trigger">` in the frontend and as `<xf:trigger ...>` in the backend (see [topmenu.xml](https://github.com/Edirom/MerMEId/blob/develop/forms/includes/topmenu.xml#L15)), have a different meaning and function than the two links which appear as `<a ...>` in the frontend and `<h:a ...>` in the backend (see [topmenu.xml](https://github.com/Edirom/MerMEId/blob/develop/forms/includes/topmenu.xml#L27)).

For now I'll try the faster solution with the CSS.

**Comment by daniel-jettka** [comment]
looks generally better now.

a bunch of graphic issues remain, e.g. with the "question mark bubbles" everywhere - will open separate issue for this

**Comment by daniel-jettka** [comment]
Some more graphical issues found by @AnastasiaWawilow 

<img width="707" alt="Bildschirmfoto 2021-07-02 um 11 36 18" src="https://user-images.githubusercontent.com/57436796/124257193-6be2c600-db2c-11eb-9c20-91c67853a1d3.png">

<img width="883" alt="Bildschirmfoto 2021-07-02 um 11 30 16" src="https://user-images.githubusercontent.com/57436796/124257217-74d39780-db2c-11eb-94d2-061b8add031b.png">

<img width="1033" alt="Bildschirmfoto 2021-07-02 um 11 30 52" src="https://user-images.githubusercontent.com/57436796/124257286-85840d80-db2c-11eb-8f87-894171344479.png">

**Comment by daniel-jettka** [comment]
Two of the three issues should be fixed, but third one is not so easy... no unique CSS selector for exactly this button group - will put this into separate issue to get this one forward...
