### ISSUE TITLE
Creation of new work

### ISSUE THREAD

**Issue by KristinaRichts** [Edirom/MerMEId#5]
Currently, it is not possible to create a new work. Could you fix this by 31.8.2020 so we can use the tool at the Edirom Summer School?

**Comment by dasch124** [comment]
It seems that the [create-file script](https://github.com/Edirom/MerMEId/blob/develop/modules/create-file.xq#L23) tries to redirect to the old orbeonform endpoint (using the config parameter @orbeon-endpoint@) which fails because being deprecated it is set to "unused" in https://github.com/Edirom/MerMEId/blob/develop/properties.xml#L5

I suppose adjusting the redirect location in @create-file.xq@ should do the trick. @MauPalantir could you try to have a look?

**Comment by MauPalantir** [comment]
right, I'll take a look
