### ISSUE TITLE
Viewing without logging in

### ISSUE THREAD

**Issue by margrethesb** [Edirom/MerMEId#73]
In an older version of MerMEId, I can open and view MerMEId/worklists without logging in. I only need to log in to edit etc.  This function doesn't exist in the new version. Can this (please) be implemented?

**Comment by daniel-jettka** [comment]
Issue confirmed. The current authentication mechanism is very (too) protective. We might need to discuss which areas/functions should be world-readable/open by default and which should be protected.

Hint for development:
The current authentication is flawed because it is only implemented in the main controller.xql but every subdirectory with its own controller.xql is lacking this authentication.
For example, the path https://mermeid.edirom.de/data/nielsen_cnw0127.xml is readable without prior authentication.

NB: data is still protected from unauthorized editing.

**Comment by daniel-jettka** [comment]
Idea:

- login/logout button on top right corner of main page of editor
- when logged in: show login name on top right corner of main page of editor
- if not logged in: functions/buttons for editing are shown in grey (maybe of hovered over: show info that login is required)
- on editing pages: for now do not show login/logout button

**Comment by daniel-jettka** [comment]
- icon for user login/logout (top-right corner) could be taken from https://icons.getbootstrap.com/

inital status - logged out:
- black icon on top-right corner, hover title "sign in"
- on-click: open modal (overlay) for login

status logged in:
- green icon (user with check), hover title "sign out"
- on-click: open modal (overlay) for confirming logout

**Comment by peterstadler** [comment]
@AnastasiaWawilow and I just opted for a redirect from `forms/*` to the `list_files.xq` page for login to avoid direct access of these pages and possible data loss when entering data.

**Comment by daniel-jettka** [comment]
Plain JS frameworks for login dialog (overlay/modal):
* https://github.com/tomloprod/tomloprodModal
* or extend: https://www.w3schools.com/howto/howto_css_overlay.asp
* or turn into plain JS: https://github.com/daniel-jettka/vikus-viewer/blob/master/js/overlayer.js
